language: node_js

node_js:
  - 9

cache:
  directories:
    - node_modules

install:
  - yarn install

before_script:
  - yarn start -- --silent &

script:
  - yarn build
  - yarn cypress:run
  - yarn test

deploy:
  provider: heroku
  app: practice-12
  api_key: $HEROKU_KEY
  on: lesson-12
